[build-system]
requires = ['setuptools', 'setuptools-scm']
build-backend = 'setuptools.build_meta'

[project]
name = 'opnieuw'
description = 'Retries for humans'
readme = 'README.md'
requires-python = '>=3.10'
keywords = []
license = {file = 'LICENSE'}
classifiers = [
    'Development Status :: 6 - Mature',
    'Intended Audience :: Developers',
    'Natural Language :: English',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
    'Programming Language :: Python :: 3.13',
    'Programming Language :: Python :: 3.14',
    'Programming Language :: Python :: 3.15',
    "Programming Language :: Python :: Implementation :: CPython",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    'Typing :: Typed'
]
dependencies = ["typing-extensions>=4.5.0;python_version<'3.13'"]
authors = [{'email' = 'ruud@channable.com'}]
dynamic = ['version']

[project.urls]
Homepage = 'https://github.com/channable/opnieuw'

[tool.setuptools.dynamic]
version = {attr = 'opnieuw.__version__'}

[tool.setuptools.package-data]
opnieuw = ['py.typed']
